#!/usr/bin/env python3
"""
Collect 250 wallets with expanded winrate criteria (70%+)
"""

import sqlite3
import logging
from typing import List, Dict
from dataclasses import dataclass

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

@dataclass
class WalletData:
    address: str
    winrate: float
    traded_total: int
    daily_trading_frequency: float
    realized_pnl_total: float
    analysis_result: str

class WalletCollectorExpanded:
    def __init__(self, db_path: str = "polymarket_notifier.db"):
        self.db_path = db_path
    
    def get_250_wallets_expanded(self) -> List[WalletData]:
        """Get 250 wallets with expanded winrate criteria (70%+)"""
        
        logger.info("Collecting 250 wallets with expanded criteria (70%+ winrate)...")
        
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            # Get all wallets with 70%+ winrate, ordered by winrate DESC, then by PnL DESC
            query = """
            SELECT address, win_rate, traded_total, daily_trading_frequency, 
                   realized_pnl_total, analysis_result
            FROM wallet_analysis_cache
            WHERE win_rate >= 0.7
            AND analysis_result = 'accepted'
            ORDER BY win_rate DESC, realized_pnl_total DESC
            LIMIT 250
            """
            
            cursor.execute(query)
            results = cursor.fetchall()
            
            wallets = []
            for row in results:
                wallet = WalletData(
                    address=row[0],
                    winrate=row[1],
                    traded_total=row[2],
                    daily_trading_frequency=row[3],
                    realized_pnl_total=row[4],
                    analysis_result=row[5]
                )
                wallets.append(wallet)
            
            conn.close()
            
            logger.info(f"Found {len(wallets)} wallets with 70%+ winrate")
            return wallets
            
        except Exception as e:
            logger.error(f"Error querying database: {e}")
            return []
    
    def get_winrate_distribution(self) -> Dict:
        """Get distribution of winrates in database"""
        
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            # Get winrate distribution
            query = """
            SELECT 
                CASE 
                    WHEN win_rate = 1.0 THEN '100%'
                    WHEN win_rate >= 0.9 THEN '90-99%'
                    WHEN win_rate >= 0.8 THEN '80-89%'
                    WHEN win_rate >= 0.7 THEN '70-79%'
                    WHEN win_rate >= 0.6 THEN '60-69%'
                    WHEN win_rate >= 0.5 THEN '50-59%'
                    ELSE 'Below 50%'
                END as winrate_range,
                COUNT(*) as count,
                SUM(realized_pnl_total) as total_pnl
            FROM wallet_analysis_cache 
            WHERE analysis_result = 'accepted'
            GROUP BY 
                CASE 
                    WHEN win_rate = 1.0 THEN '100%'
                    WHEN win_rate >= 0.9 THEN '90-99%'
                    WHEN win_rate >= 0.8 THEN '80-89%'
                    WHEN win_rate >= 0.7 THEN '70-79%'
                    WHEN win_rate >= 0.6 THEN '60-69%'
                    WHEN win_rate >= 0.5 THEN '50-59%'
                    ELSE 'Below 50%'
                END
            ORDER BY win_rate DESC
            """
            
            cursor.execute(query)
            results = cursor.fetchall()
            
            distribution = {}
            for row in results:
                distribution[row[0]] = {
                    'count': row[1],
                    'total_pnl': row[2] or 0
                }
            
            conn.close()
            
            return distribution
            
        except Exception as e:
            logger.error(f"Error getting distribution: {e}")
            return {}
    
    def save_expanded_250_to_txt(self, wallets: List[WalletData], filename: str = "wallets_250_expanded.txt"):
        """Save expanded set of 250 wallets to .txt file"""
        
        logger.info(f"Saving {len(wallets)} wallets to {filename}...")
        
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                # Write header
                f.write("# Polymarket Wallets - Expanded Set of 250 (70%+ Winrate)\n")
                f.write("# Format: address,winrate%,trades,daily_frequency,pnl_total\n")
                f.write("# Generated by Polymarket Notifier\n")
                f.write("# Criteria: 70%+ winrate, accepted wallets\n\n")
                
                # Group wallets by winrate ranges
                wallets_100 = [w for w in wallets if w.winrate == 1.0]
                wallets_90_99 = [w for w in wallets if w.winrate >= 0.9 and w.winrate < 1.0]
                wallets_80_89 = [w for w in wallets if w.winrate >= 0.8 and w.winrate < 0.9]
                wallets_70_79 = [w for w in wallets if w.winrate >= 0.7 and w.winrate < 0.8]
                
                # Write 100% winrate section
                if wallets_100:
                    f.write("# === 100% WINRATE WALLETS ===\n")
                    for i, wallet in enumerate(wallets_100, 1):
                        f.write(f"{i:3d}. {wallet.address} | "
                               f"Winrate: {wallet.winrate*100:.1f}% | "
                               f"Trades: {wallet.traded_total} | "
                               f"Daily: {wallet.daily_trading_frequency:.2f} | "
                               f"PnL: ${wallet.realized_pnl_total:,.2f}\n")
                
                # Write 90-99% winrate section
                if wallets_90_99:
                    f.write(f"\n# === 90-99% WINRATE WALLETS ===\n")
                    start_num = len(wallets_100) + 1
                    for i, wallet in enumerate(wallets_90_99, start_num):
                        f.write(f"{i:3d}. {wallet.address} | "
                               f"Winrate: {wallet.winrate*100:.1f}% | "
                               f"Trades: {wallet.traded_total} | "
                               f"Daily: {wallet.daily_trading_frequency:.2f} | "
                               f"PnL: ${wallet.realized_pnl_total:,.2f}\n")
                
                # Write 80-89% winrate section
                if wallets_80_89:
                    f.write(f"\n# === 80-89% WINRATE WALLETS ===\n")
                    start_num = len(wallets_100) + len(wallets_90_99) + 1
                    for i, wallet in enumerate(wallets_80_89, start_num):
                        f.write(f"{i:3d}. {wallet.address} | "
                               f"Winrate: {wallet.winrate*100:.1f}% | "
                               f"Trades: {wallet.traded_total} | "
                               f"Daily: {wallet.daily_trading_frequency:.2f} | "
                               f"PnL: ${wallet.realized_pnl_total:,.2f}\n")
                
                # Write 70-79% winrate section
                if wallets_70_79:
                    f.write(f"\n# === 70-79% WINRATE WALLETS ===\n")
                    start_num = len(wallets_100) + len(wallets_90_99) + len(wallets_80_89) + 1
                    for i, wallet in enumerate(wallets_70_79, start_num):
                        f.write(f"{i:3d}. {wallet.address} | "
                               f"Winrate: {wallet.winrate*100:.1f}% | "
                               f"Trades: {wallet.traded_total} | "
                               f"Daily: {wallet.daily_trading_frequency:.2f} | "
                               f"PnL: ${wallet.realized_pnl_total:,.2f}\n")
                
                # Write summary
                f.write(f"\n# Summary:\n")
                f.write(f"# Total wallets: {len(wallets)}\n")
                f.write(f"# 100% winrate: {len(wallets_100)}\n")
                f.write(f"# 90-99% winrate: {len(wallets_90_99)}\n")
                f.write(f"# 80-89% winrate: {len(wallets_80_89)}\n")
                f.write(f"# 70-79% winrate: {len(wallets_70_79)}\n")
                f.write(f"# Total PnL: ${sum(w.realized_pnl_total for w in wallets):,.2f}\n")
                f.write(f"# Average trades per wallet: {sum(w.traded_total for w in wallets) / len(wallets):.1f}\n")
                f.write(f"# Average daily frequency: {sum(w.daily_trading_frequency for w in wallets) / len(wallets):.2f}\n")
                f.write(f"# Average winrate: {sum(w.winrate for w in wallets) / len(wallets)*100:.2f}%\n")
            
            logger.info(f"✅ Successfully saved to {filename}")
            return True
            
        except Exception as e:
            logger.error(f"Error saving to file: {e}")
            return False

def main():
    """Main function to collect expanded set of 250 wallets"""
    logger.info("Starting collection of expanded 250 wallet set...")
    
    collector = WalletCollectorExpanded()
    
    # Get winrate distribution first
    distribution = collector.get_winrate_distribution()
    if distribution:
        logger.info("Winrate Distribution:")
        for range_name, data in distribution.items():
            logger.info(f"  {range_name}: {data['count']} wallets, PnL: ${data['total_pnl']:,.2f}")
    
    # Collect expanded set
    all_wallets = collector.get_250_wallets_expanded()
    
    if all_wallets:
        logger.info(f"🎉 Collected {len(all_wallets)} wallets total!")
        
        # Show breakdown by winrate ranges
        wallets_100 = [w for w in all_wallets if w.winrate == 1.0]
        wallets_90_99 = [w for w in all_wallets if w.winrate >= 0.9 and w.winrate < 1.0]
        wallets_80_89 = [w for w in all_wallets if w.winrate >= 0.8 and w.winrate < 0.9]
        wallets_70_79 = [w for w in all_wallets if w.winrate >= 0.7 and w.winrate < 0.8]
        
        logger.info(f"  - 100% winrate: {len(wallets_100)} wallets")
        logger.info(f"  - 90-99% winrate: {len(wallets_90_99)} wallets")
        logger.info(f"  - 80-89% winrate: {len(wallets_80_89)} wallets")
        logger.info(f"  - 70-79% winrate: {len(wallets_70_79)} wallets")
        
        # Show top 10 overall
        logger.info("Top 10 wallets by PnL:")
        for i, wallet in enumerate(all_wallets[:10], 1):
            logger.info(f"  {i:2d}. {wallet.address} - "
                       f"Winrate: {wallet.winrate*100:.1f}%, "
                       f"PnL: ${wallet.realized_pnl_total:,.2f}, "
                       f"Trades: {wallet.traded_total}")
        
        # Save to file
        success = collector.save_expanded_250_to_txt(all_wallets)
        
        if success:
            logger.info("✅ Expanded file saved successfully!")
        else:
            logger.error("❌ Failed to save file!")
    else:
        logger.warning("⚠️  No wallets found!")
    
    return all_wallets

if __name__ == "__main__":
    wallets = main()
