#!/usr/bin/env python3
"""
Collect 250 wallets with 100% winrate and save to .txt file
"""

import sqlite3
import logging
from typing import List, Dict
from dataclasses import dataclass

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

@dataclass
class WalletData:
    address: str
    winrate: float
    traded_total: int
    daily_trading_frequency: float
    realized_pnl_total: float
    analysis_result: str

class WalletCollector:
    def __init__(self, db_path: str = "polymarket_notifier.db"):
        self.db_path = db_path
    
    def get_100_percent_wallets(self, limit: int = 250) -> List[WalletData]:
        """Get wallets with 100% winrate"""
        
        logger.info(f"Collecting {limit} wallets with 100% winrate...")
        
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            # Query wallets with 100% winrate (stored as 1.0 in database)
            query = """
            SELECT address, win_rate, traded_total, daily_trading_frequency, 
                   realized_pnl_total, analysis_result
            FROM wallet_analysis_cache
            WHERE win_rate = 1.0
            AND analysis_result = 'accepted'
            ORDER BY realized_pnl_total DESC
            LIMIT ?
            """
            
            cursor.execute(query, (limit,))
            results = cursor.fetchall()
            
            wallets = []
            for row in results:
                wallet = WalletData(
                    address=row[0],
                    winrate=row[1],
                    traded_total=row[2],
                    daily_trading_frequency=row[3],
                    realized_pnl_total=row[4],
                    analysis_result=row[5]
                )
                wallets.append(wallet)
            
            conn.close()
            
            logger.info(f"Found {len(wallets)} wallets with 100% winrate")
            return wallets
            
        except Exception as e:
            logger.error(f"Error querying database: {e}")
            return []
    
    def save_to_txt(self, wallets: List[WalletData], filename: str = "wallets_100_percent_winrate.txt"):
        """Save wallets to .txt file"""
        
        logger.info(f"Saving {len(wallets)} wallets to {filename}...")
        
        try:
            with open(filename, 'w', encoding='utf-8') as f:
                # Write header
                f.write("# Polymarket Wallets with 100% Winrate\n")
                f.write("# Format: address,winrate%,trades,daily_frequency,pnl_total\n")
                f.write("# Generated by Polymarket Notifier\n\n")
                
                # Write wallets
                for i, wallet in enumerate(wallets, 1):
                    f.write(f"{i:3d}. {wallet.address} | "
                           f"Winrate: {wallet.winrate*100:.1f}% | "
                           f"Trades: {wallet.traded_total} | "
                           f"Daily: {wallet.daily_trading_frequency:.2f} | "
                           f"PnL: ${wallet.realized_pnl_total:,.2f}\n")
                
                # Write summary
                f.write(f"\n# Summary:\n")
                f.write(f"# Total wallets: {len(wallets)}\n")
                f.write(f"# Total PnL: ${sum(w.realized_pnl_total for w in wallets):,.2f}\n")
                f.write(f"# Average trades per wallet: {sum(w.traded_total for w in wallets) / len(wallets):.1f}\n")
                f.write(f"# Average daily frequency: {sum(w.daily_trading_frequency for w in wallets) / len(wallets):.2f}\n")
            
            logger.info(f"✅ Successfully saved to {filename}")
            return True
            
        except Exception as e:
            logger.error(f"Error saving to file: {e}")
            return False
    
    def get_statistics(self) -> Dict:
        """Get statistics about 100% winrate wallets"""
        
        try:
            conn = sqlite3.connect(self.db_path)
            cursor = conn.cursor()
            
            # Get count of 100% winrate wallets
            cursor.execute("SELECT COUNT(*) FROM wallet_analysis_cache WHERE win_rate = 1.0 AND analysis_result = 'accepted'")
            count_100_percent = cursor.fetchone()[0]
            
            # Get total PnL
            cursor.execute("SELECT SUM(realized_pnl_total) FROM wallet_analysis_cache WHERE win_rate = 1.0 AND analysis_result = 'accepted'")
            total_pnl = cursor.fetchone()[0] or 0
            
            # Get average trades
            cursor.execute("SELECT AVG(traded_total) FROM wallet_analysis_cache WHERE win_rate = 1.0 AND analysis_result = 'accepted'")
            avg_trades = cursor.fetchone()[0] or 0
            
            # Get average daily frequency
            cursor.execute("SELECT AVG(daily_trading_frequency) FROM wallet_analysis_cache WHERE win_rate = 1.0 AND analysis_result = 'accepted'")
            avg_daily = cursor.fetchone()[0] or 0
            
            conn.close()
            
            return {
                'count_100_percent': count_100_percent,
                'total_pnl': total_pnl,
                'avg_trades': avg_trades,
                'avg_daily_frequency': avg_daily
            }
            
        except Exception as e:
            logger.error(f"Error getting statistics: {e}")
            return {}

def main():
    """Main function to collect and save 100% winrate wallets"""
    logger.info("Starting collection of 100% winrate wallets...")
    
    collector = WalletCollector()
    
    # Get statistics first
    stats = collector.get_statistics()
    if stats:
        logger.info("Statistics:")
        logger.info(f"  Total 100% winrate wallets: {stats['count_100_percent']}")
        logger.info(f"  Total PnL: ${stats['total_pnl']:,.2f}")
        logger.info(f"  Average trades: {stats['avg_trades']:.1f}")
        logger.info(f"  Average daily frequency: {stats['avg_daily_frequency']:.2f}")
    
    # Collect wallets
    wallets = collector.get_100_percent_wallets(limit=250)
    
    if wallets:
        logger.info(f"🎉 Collected {len(wallets)} wallets with 100% winrate!")
        
        # Show top 10
        logger.info("Top 10 wallets by PnL:")
        for i, wallet in enumerate(wallets[:10], 1):
            logger.info(f"  {i:2d}. {wallet.address} - "
                       f"PnL: ${wallet.realized_pnl_total:,.2f}, "
                       f"Trades: {wallet.traded_total}, "
                       f"Daily: {wallet.daily_trading_frequency:.2f}")
        
        # Save to file
        success = collector.save_to_txt(wallets)
        
        if success:
            logger.info("✅ File saved successfully!")
        else:
            logger.error("❌ Failed to save file!")
    else:
        logger.warning("⚠️  No wallets found!")
    
    return wallets

if __name__ == "__main__":
    wallets = main()
