#!/usr/bin/env python3
"""
Ручной способ получения Topic ID через @RawDataBot
"""
import os
from dotenv import load_dotenv

load_dotenv()

CHAT_ID = os.getenv("TELEGRAM_REPORTS_CHAT_ID") or os.getenv("TELEGRAM_CHAT_ID")

print("=" * 70)
print("📋 РУЧНОЙ СПОСОБ ПОЛУЧЕНИЯ TOPIC ID")
print("=" * 70)
print()
print("Используйте @RawDataBot для получения точных Topic ID:")
print()
print("ШАГ 1: Добавьте @RawDataBot в канал")
print("1. Откройте канал 'POLY DAO TEST' в Telegram")
print("2. Нажмите на название канала вверху")
print("3. Выберите 'Add Members' или 'Добавить участников'")
print("4. Найдите и добавьте @RawDataBot")
print()
print("ШАГ 2: Получите Topic ID для 'Low Size Alerts'")
print("1. Откройте тему 'Low Size Alerts' в канале")
print("2. Отправьте любое сообщение в этой теме (например, 'test')")
print("3. @RawDataBot автоматически ответит с данными сообщения")
print("4. В ответе найдите поле 'message_thread_id' - это и есть Topic ID!")
print("   Пример: \"message_thread_id\": 2")
print()
print("ШАГ 3: Получите Topic ID для 'High Size Alerts'")
print("1. Откройте тему 'High Size Alerts' в канале")
print("2. Отправьте любое сообщение в этой теме (например, 'test')")
print("3. @RawDataBot автоматически ответит с данными сообщения")
print("4. Найдите 'message_thread_id' в ответе")
print()
print("=" * 70)
print("📝 ПОСЛЕ ПОЛУЧЕНИЯ ID")
print("=" * 70)
print()
print("Добавьте в файл .env следующие строки:")
print()
print(f"TELEGRAM_REPORTS_CHAT_ID={CHAT_ID}")
print("TELEGRAM_LOW_SIZE_TOPIC_ID=<ID_из_RawDataBot_для_Low_Size>")
print("TELEGRAM_HIGH_SIZE_TOPIC_ID=<ID_из_RawDataBot_для_High_Size>")
print("SIZE_THRESHOLD_USD=10000")
print()
print("=" * 70)
print("💡 АЛЬТЕРНАТИВНЫЙ СПОСОБ")
print("=" * 70)
print()
print("Если @RawDataBot не работает, попробуйте:")
print()
print("1. Откройте канал в Telegram Desktop (компьютерная версия)")
print("2. Откройте тему 'Low Size Alerts'")
print("3. Правой кнопкой мыши на любое сообщение → 'Copy Message Link'")
print("4. В ссылке может быть виден topic ID")
print()
print("Или просто укажите ID вручную, если вы их знаете:")
print("(Обычно это небольшие числа: 1, 2, 3, 4 и т.д.)")
print()

